name: Build Docker images 

on:
  push: 
    branches:
      - '*'
    tags:
      - '*'

jobs: 
  build:
    name: Build Docker image 
    runs-on: ubuntu-latest
    environment: scipy-dev
    if: "github.repository_owner == 'trallard' && !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip github]')"
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Lint Docker 
        uses: brpaz/hadolint-action@v1.2.1
        with: 
          dockerfile: ./tools/docker_dev/Dockerfile
      - name: Get refs
        shell: bash
        run: |
          export raw_branch=${GITHUB_REF#refs/heads/}
          echo "::set-output name=branch::${raw_branch//\//-}"
          echo "::set-output name=date::$(date +'%Y%m%d')"
          echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
          echo "::set-output name=longtag::$(echo ${{ steps.getrefs.outputs.date }}-${{ steps.getrefs.outputs.branch}}-${{ steps.getrefs.outputs.sha8 }})"
        id: getrefs
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: "./tools/docker_dev"
          file: "./tools/docker_dev/Dockerfile"
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            trallard/scipy-dev:${{ steps.getrefs.outputs.date }}-${{ steps.getrefs.outputs.branch}}-${{ steps.getrefs.outputs.sha8 }}, trallard/scipy-dev:latest
      - name: Update Dockerfile 
        run: |
          git config --local user.name github-actions 
          git config --local user.email github-actions@github.com
          echo '${{ steps.getrefs.outputs.longtag }}'
          sed -E -i '' "s/[0-9]{8}\-master\-[a-z0-9]{8}/${{ steps.getrefs.outputs.longtag }}/" ${{ github.workspace}}/tools/docker_dev/.gitpod.Dockerfile
          git add .
          git commit -m "MAN: Update gitpod Dockerfile"
          git push